version: '3.4'

services:
  node_1:
    build:
      context: ../
      dockerfile: ./likecoin/Dockerfile
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/likecoin/chain.json
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.liked