name: publish
on:
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: akash
            version: v0.12.1
          - project: sentinelhub
            version: v0.8.3
          - project: gaia
            version: v5.0.8
          - project: kava
            version: v0.15.1
          - project: osmosis
            version: v4.2.0
          - project: persistence
            version: v0.1.3
          - project: juno
            version: v1.0.0
          - project: regen
            version: v2.0.0
          - project: stargaze
            version: v1.0.0
          - project: terra
            version: v0.5.9
          - project: sifchain
            version: v0.9.14
          - project: bitcanna
            version: v1.2
          - project: emoney
            version: v1.1.3
          - project: bitsong
            version: v0.8.0
          - project: cryptoorgchain
            version: v3.1.1-croeseid
          - project: impacthub
            version: v1.6.0
          - project: band
            version: v2.3.2
          - project: kichain
            version: 2.0.0
          - project: likecoin
            version: fotan-1.1
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          # Create dummy env file
          touch .env
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          cd ${{matrix.project}}
          docker-compose build
          docker tag ${{matrix.project}}_node_1:latest ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}}${{matrix.tag_suffix}}
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}}${{matrix.tag_suffix}}
